# Site settings
title: Matt DePero
header-img: img/home-bg.jpg
email: deperomd@gmail.com
description: "Projects, ideas, and resume by Matthew DePero, a computer science student at Miami University from the hometown of Wadsworth, Ohio."
baseurl: "/college_landing"
url: "https://mattdepero.com"
twitter_username: mattdepero
github_username:  mdepero
facebook_username:  

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "projects/page:num"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
plugins: [jekyll-paginate]
