# Site settings
title: Matt DePero
header-img: img/home-bg.jpg
email: deperomd@gmail.com
description: "A place for hosting projects and ideas by Matthew DePero, a computer science student at Miami University from the hometown of Wadsworth, Ohio."
baseurl: ""
url: "http://mattdepero.com"
twitter_username: mattdepero
github_username:  mdepero
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
